version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.2
  python: circleci/python@1.3.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm install jest --save-dev
            - run: npm run build
            - run: npm run test
      - codecov/upload:
          file: "./coverage/clover.xml"
          token: bc55e615-594b-40a3-bf51-3e408a8e5f85
  eslint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run eslint
  build-typescript:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run build
  deploy-docs:
    machine:
      image: ubuntu-1604:202004-01 ubuntu-2004:202010-01
    steps:
      - checkout
      - run: pip install mkdocs mkdocs-material
      - run: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - node/with-cache:
          steps:
            - run: npm run create-docs
workflows:
  build-and-test:
    jobs:
      - eslint
      - build-typescript
      - build-and-test
      - deploy-docs
